parameters:
#    pfe_session.example.class: Pfe\Bundle\SessionBundle\Example

services:
#    pfe_session.example:
#        class: %pfe_session.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
