<?php

namespace Pfe\Bundle\CoursesBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SourahRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourahRepository extends EntityRepository
{
}
