user:
    pattern:  /
    defaults: { _controller: "PfeUserBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "PfeUserBundle:User:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "PfeUserBundle:User:new" }

user_test:
    pattern:  /test
    defaults: { _controller: "PfeUserBundle:User:test" }

user_create:
    pattern:  /create
    defaults: { _controller: "PfeUserBundle:User:create" }
    requirements: { _method: post|get }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PfeUserBundle:User:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "PfeUserBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PfeUserBundle:User:delete" }

user_lister:
    pattern:  /lister
    defaults: { _controller: "PfeUserBundle:User:lister" }

pfe_user_rechercher:
  pattern: /user/rechercher
  defaults: { _controller: PfeUserBundle:User:rechercher }
  requirements:
    _method: POST