pfe_frontend:
    resource: "@PfeFrontendBundle/Resources/config/routing.yml"
    prefix:   /

pfe_horal_test:
    resource: "@PfeHoralTestBundle/Resources/config/routing.yml"
    prefix:   /

pfe_examen:
    resource: "@PfeExamenBundle/Resources/config/routing.yml"
    prefix:   /

pfe_session:
    resource: "@PfeSessionBundle/Resources/config/routing.yml"
    prefix:   /

pfe_courses:
    resource: "@PfeCoursesBundle/Resources/config/routing.yml"
    prefix:   /

pfe_web_bundle:
    resource: "@PfeWebBundle/Resources/config/routing.yml"
    prefix:   /