<?php

namespace Pfe\Bundle\ExamenBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeexamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeexamenRepository extends EntityRepository
{
}
