<?php

namespace Pfe\Bundle\SessionBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PresenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresenceRepository extends EntityRepository
{
}
