parameters:
#    pfe_courses.example.class: Pfe\Bundle\CoursesBundle\Example

services:
#    pfe_courses.example:
#        class: %pfe_courses.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
