parameters:
    pfe_user.registration.class: Pfe\Bundle\UserBundle\Form\StudentRegistration

services:
    pfe_user.registration.form:
        class: %pfe_user.registration.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: pfe_user_registration }